/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vkknY4BHMhH
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { FC } from 'react';

import { OwnersTable } from './owners-table';

interface DashboardProps {
  search?: string;
}
const Dashboard: FC<DashboardProps> = async () => {
  return (
    <div>
      <OwnersTable />
    </div>
  );
};

export default Dashboard;
