/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XF0mWfiJGn7
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from 'next/link';

export function NotFound() {
  return (
    <div className="flex flex-col items-center justify-center h-screen ">
      <div className="max-w-md px-4 py-8 space-y-4 text-center">
        <DogIcon className="mx-auto h-20 w-20 text-gray-500 " />
        <h1 className="text-3xl font-bold text-gray-900 ">
          {`Ups! Pagina no encontrada!`}
        </h1>
        <p className="text-gray-500 ">
          {`La pagina que buscas ha sido movida o no existe.`}
        </p>
        <Link
          className="inline-flex items-center justify-center rounded-md bg-primary-600 px-4 py-2 text-sm font-medium text-black shadow-sm hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 "
          href="/"
        >
          {`Volver al inicio`}
        </Link>
      </div>
    </div>
  );
}

function DogIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 5.172C10 3.782 8.423 2.679 6.5 3c-2.823.47-4.113 6.006-4 7 .08.703 1.725 1.722 3.656 1 1.261-.472 1.96-1.45 2.344-2.5" />
      <path d="M14.267 5.172c0-1.39 1.577-2.493 3.5-2.172 2.823.47 4.113 6.006 4 7-.08.703-1.725 1.722-3.656 1-1.261-.472-1.855-1.45-2.239-2.5" />
      <path d="M8 14v.5" />
      <path d="M16 14v.5" />
      <path d="M11.25 16.25h1.5L12 17l-.75-.75Z" />
      <path d="M4.42 11.247A13.152 13.152 0 0 0 4 14.556C4 18.728 7.582 21 12 21s8-2.272 8-6.444c0-1.061-.162-2.2-.493-3.309m-9.243-6.082A8.801 8.801 0 0 1 12 5c.78 0 1.5.108 2.161.306" />
    </svg>
  );
}
